config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :order_lines
  resources :orders
  resources :purchase_orders
  resources :sales_orders

  resources :supplier_order_lines
  resources :supplier_orders
  resources :suppliers
  resources :items
  resources :bill_of_material_lines
  resources :bill_of_materials do
    post :import, on: :collection
    get 'components'
    get 'groups'
    get 'import_purchase_order'
    get 'purchase_order_groups'
  end
  get 'components_csv', action: :components, controller: 'bill_of_materials'
  get 'groups_csv', action: :groups, controller: 'bill_of_materials'
  get 'purchase_order_groups_csv', action: :purchase_order_groups, controller: 'bill_of_materials'
  get 'add_component_to_supplier_order', action: :add_component_to_supplier_order, controller: 'purchase_orders'
  get 'send_purchase_order_email', action: :send_email, controller: 'purchase_orders'
  get 'clear_supplier_order', action: :clear_supplier_order, controller: 'supplier_orders'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'bill_of_materials#index'
end

app/models/supplier_order.rb
class SupplierOrder < ApplicationRecord
  belongs_to :supplier
  belongs_to :bill_of_material
  has_many :supplier_order_lines, dependent: :destroy
  has_many :items, through: :supplier_order_lines
  auto_increment :number, initial: "ORD-FOR-#{Date.today.year}-0001"

  def add_component_to_order(bill_of_material_line)
    existing = supplier_order_lines.find_by(item_id: bill_of_material_line.component.id)

    if existing.present?
      existing.update(quantity: [existing.quantity + 1, bill_of_material_line.quantity].min)
    else
      supplier_order_lines.create!(
        item_id: bill_of_material_line.component.id,
        quantity: 1,
        name: bill_of_material_line.component.name,
        code: bill_of_material_line.component.code
      )
    end

    button = bill_of_material_lines.find { |line| line.component.code == bill_of_material_line.component.code }

    return unless button.present? && button.quantity.positive?

    button.update(quantity: button.quantity - 1)
  end
end

app/models/supplier_orders/builder.rb
# session_initializer.rb
module SupplierOrders
  class Builder
    def initialize(bill_of_material)
      @bill_of_material = bill_of_material
    end

    def initialize_session_variables(session)
      session_buttons = "bill_of_material_#{@bill_of_material.id}_bill_of_material_lines"
      session_sales_order_lines = "supplier_order_#{@bill_of_material.id}_supplier_order_lines"

      session[session_buttons] ||= []

      if session[session_buttons].empty?
        session[session_buttons] =
          @bill_of_material.bill_of_material_lines.includes([:component])
      end

      session[session_sales_order_lines] ||= []
    end
  end
end

app/models/supplier_orders/component_adder.rb
# supplier_order_manager.rb
module SupplierOrders
  class ComponentAdder
    attr_reader :bill_of_material_line, :bill_of_material

    def initialize(bill_of_material_line, session, flash)
      @bill_of_material_line = bill_of_material_line
      @bill_of_material = bill_of_material_line.bill_of_material
      @session = session
      @flash = flash
    end

    def add_component_to_supplier_order
      update_supplier_order
      update_buttons
    end

    private

    def update_supplier_order
      supplier_order_lines = @session["supplier_order_#{bill_of_material.id}_supplier_order_lines"]
      existing_line = supplier_order_lines.find { |line| line[:code] == bill_of_material_line.component.code }

      if supplier_order_lines.present? && existing_line.present?
        existing_line[:quantity] += 1 if existing_line[:quantity] < bill_of_material_line.quantity
        existing_line[:to_order] -= 0 if bill_of_material_line.to_order > 0

      else
        supplier_order_lines.push(
          item_id: bill_of_material_line.component.id,
          quantity: 1,
          ordered: bill_of_material_line.ordered,
          to_order: bill_of_material_line.to_order - 1,
          name: bill_of_material_line.component.name,
          code: bill_of_material_line.component.code
        )
      end
    end

    def update_buttons
      session_buttons = @session["bill_of_material_#{@bill_of_material.id}_bill_of_material_lines"]
      button = session_buttons
               .find { |line| line.component.code == bill_of_material_line.component.code }
      return unless button.present? && button[:quantity].to_i.positive?

      button[:quantity] -= 1
      @flash[:notice] =
        "Componente #{bill_of_material_line.component.code} #{bill_of_material_line.component.name} aggiunto all'ordine!"
    end
  end
end

app/controllers/supplier_orders_controller.rb
class SupplierOrdersController < ApplicationController
  before_action :set_supplier_order, only: %i[show edit update destroy send_email add_component_to_supplier_order]

  # GET /supplier_orders
  def index
    @supplier_orders = SupplierOrder.includes([:supplier])
  end

  # GET /supplier_orders/1
  def show; end

  # GET /supplier_orders/new
  def new
    @suppliers = Supplier.all
    @bill_of_material = BillOfMaterial.find(params[:bill_of_material_id])
    @bill_of_material_lines = @bill_of_material.bill_of_material_lines.order(component_id: :asc)
    @supplier_order = @bill_of_material.supplier_orders.create(bill_of_material_id: @bill_of_material.id,
                                                               date: Date.today)
    @component_buttons = @bill_of_material.purchase_orders.first.order_lines
  end

  def new_supplier_order_from_bill_of_material
    @suppliers = Supplier.all
    @bill_of_material = BillOfMaterial.find(params[:bill_of_material_id])
    @bill_of_material_lines = @bill_of_material.bill_of_material_lines
    session_initializer = SupplierOrders::Builder.new(@bill_of_material)
    session_initializer.initialize_session_variables(session)
    @supplier_order = SupplierOrder.new(bill_of_material_id: @bill_of_material.id, date: Date.today)
  end

  def add_component_to_supplier_order
    @component_buttons = @bill_of_material.purchase_orders.first.order_lines

    @bill_of_material_line = BillOfMaterialLine.find(params[:line])
    @bill_of_material = @bill_of_material_line.bill_of_material
    @bill_of_material_lines = @bill_of_material.bill_of_material_lines.order(component_id: :asc)
    @supplier_order_line = @supplier_order.supplier_order_lines.find_by(item_id: @bill_of_material_line.component.id)
    @updated = false
    if @supplier_order_line.present?
      @updated = true
      if @bill_of_material_line.quantity > @supplier_order_line.quantity
        @supplier_order_line.quantity = @supplier_order_line.quantity + 1
      end
      @supplier_order_line.save
    else
      @supplier_order_line = @supplier_order.supplier_order_lines.create(item_id: @bill_of_material_line.component.id,
                                                                         quantity: 1)

    end
    if @bill_of_material_line.quantity > @bill_of_material_line.ordered
      @bill_of_material_line.ordered = @bill_of_material_line.ordered + 1
    end
    @bill_of_material_line.to_order = @bill_of_material_line.to_order - 1 if @bill_of_material_line.to_order.positive?
    @bill_of_material_line.save
    @supplier_order_line
  end

  # GET /supplier_orders/1/edit
  def edit
    @bill_of_material = @supplier_order.bill_of_material
    @component_buttons = @bill_of_material.purchase_orders.first.order_lines
  end

  # POST /supplier_orders
  def create
    @supplier_order = SupplierOrder.new(supplier_order_params)

    if @supplier_order.save!
      # session["supplier_order_#{@supplier_order.bill_of_material_id}_supplier_order_lines"].each do |line|
      #   @supplier_order.supplier_order_lines.create!(item_id: line[:item_id], quantity: line[:quantity])
      # end
      # session["supplier_order_#{@supplier_order.bill_of_material_id}_supplier_order_lines"] = []
      # session["bill_of_material_#{@supplier_order.bill_of_material_id}_bill_of_material_lines"] = []

      redirect_to edit_supplier_order_path(@supplier_order)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def send_email
    SupplierOrderMailer.with(supplier_order: @supplier_order).new_supplier_order_email.deliver_later
    redirect_to @supplier_order, notice: 'Email inviata al fornitore con successo!'
  end

  # PATCH/PUT /supplier_orders/1
  def update
    if @supplier_order.update(supplier_order_params)
      redirect_to @supplier_order, notice: 'Supplier order was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /supplier_orders/1
  def destroy
    @supplier_order.destroy!
    redirect_to supplier_orders_url, notice: 'Ordine fornitore distrutto con successo!', status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_supplier_order
    @supplier_order = SupplierOrder.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def supplier_order_params
    params.require(:supplier_order).permit(:number, :supplier_id, :date, :bill_of_material_id, :machine)
  end
end

app/helpers/supplier_orders_helper.rb
module SupplierOrdersHelper
  def suppliers_for_select
    Manufacturer.all.collect { |m| [m.name] }
  end
end

app/views/supplier_orders/_form.html.erb
<%= simple_form_for @supplier_order, class: "contents" do |form| %>
  <% if supplier_order.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(supplier_order.errors.count, "error") %> prohibited this supplier_order from being saved:</h2>
      <ul>
        <% supplier_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="bg-gray-dark p-4 rounded-lg my-4">
    <div class="grid grid-cols-3 gap-4">
      <%= form.input :bill_of_material_id, label: false, :as => :hidden %>
      <% if @supplier_order.supplier.blank? %>
        <div>
          <%= form.label :"Fornitore", class: "label" %>
          <%= form.input :supplier_id, collection: @suppliers, label: false, input_html: { class: "block shadow rounded-md border border-gray outline-none px-3 py-2 mt-2 w-full" }  %>
        </div>
      <% else %>
        <div>
          <%= form.label :"Fornitore", class: "label" %>
          <%= form.input :supplier_id, disabled: true, collection: @suppliers, label: false, input_html: { class: "block shadow rounded-md border border-gray outline-none px-3 py-2 mt-2 w-full" }  %>
        </div>
        <div>
          <%= form.label "Data", class: "label" %>
          <%= form.input :date, label: false, as: :date, html5: true, input_html: { class: "block shadow rounded-md border border-gray outline-none px-3 py-2 mt-2 w-full" }  %>
        </div>
        <div>
          <%= form.label "Numero", class: "label" %>
          <%= form.input :number, label: false, input_html: { class: "block shadow rounded-md border border-gray outline-none px-3 py-2 mt-2 w-full" }  %>
        </div>
        <div>
          <%= form.label "Distinta", class: "label" %>
          <br>
          <p class='btn-primary mt-2'><%=  @supplier_order.bill_of_material.number %></p>
        </div>
        <div>
          <%= form.label "Macchina", class: "label" %>
          <%= form.input :machine, label: false, input_html: { class: "block shadow rounded-md border border-gray outline-none px-3 py-2 mt-2 w-full" } %>
        </div>
        <div>
          <%= form.label "Macchina", class: "label" %>
          <%= form.input :machine, label: false, input_html: { class: "block shadow rounded-md border border-gray outline-none px-3 py-2 mt-2 w-full" } %>
        </div>
      <% end %>
    </div>
    <div class="align-middle text-right mt-8 flex gap-2 items-bottom justify-end">
      <%= link_to "Cancella", clear_supplier_order_path(id: @supplier_order.bill_of_material.id), data: {turbo_stream: true}, class: "btn-primary" %>
      <%= form.submit "Crea ordine", class: "btn-positive" if @supplier_order.id.blank? %>
      <%= form.submit "Salva", class: "btn-positive" if @supplier_order.id.present? %>
    </div>
  </div>
<% end %>

app/views/supplier_orders/_line.html.erb
<tr id="<%= line[:code] %>" is="turbo-frame" class="bg-blue text-light">
  <td  class="px-6 py-4 font-medium text-blue-50 whitespace-nowrap dark:text-blue-100">
      <%= line[:code] %>
  </td>
  <td scope="row" class="px-6 py-4 font-medium text-blue-50 whitespace-nowrap dark:text-blue-100">
      <%= line[:name] %>
  </td>
  <td class="px-6 py-4">
    <%= line[:quantity].to_i %>
  </td>
</tr>   

app/views/supplier_orders/_supplier_component_buttons.html.erb
<% @component_buttons.each do | line | %>
  <div class="btn-positive <%= 'bg-gray' if line.quantity.to_i.zero? %> mb-2 ">
    <div class="flex items-center justify-between">
      <%= link_to line.component.code,
      add_component_to_supplier_order_path(line: line["id"], id: @order.id),
      data: {
        turbo_stream: true,
      } %>
      <p
        class="
          text-center font-bold text-light bg-gray-dark py-2 px-4 ml-2 rounded-lg
        "
      ><%= line.quantity.to_i %></p>
    </div>
  </div>
<% end %>

app/views/supplier_orders/_supplier_order.html.erb
<div id="<%= dom_id supplier_order %>">
  <div class="flex justify-between items-center">
    <h1 class="p-4 font-bold text-4xl text-gray-dark">Ordine Fornitore
      <%= supplier_order.number %></h1>
    <div class="flex gap-2">
      <%= link_to "Modifica",
      edit_supplier_order_path(id: supplier_order.id),
      class: "rounded-lg p-2  bg-green text-light block font-medium" %>
      <%= link_to "Invia email",
      send_supplier_order_email_path(id: supplier_order.id),
      class: "rounded-lg p-2  bg-green text-light block font-medium" %>
    </div>
  </div>
  <div class="flex gap-2 text-light mt-4 p-4">
    <div class="px-4 bg-gray-dark p-2 rounded">
      <strong class="block font-bold mb-1">Fornitore</strong>
      <%= supplier_order.supplier.name %>
    </div>
    <div class="px-4 bg-gray-dark p-2 rounded">
      <strong class="block font-bold mb-1">Data</strong>
      <%= supplier_order.date %>
    </div>
    <div class="px-4 bg-gray-dark p-2 rounded">
      <strong class="block font-bold mb-1">Numero</strong>
      <%= supplier_order.number %>
    </div>
    <div class="px-4 bg-gray-dark p-2 rounded">
      <strong class="block font-bold mb-1">Componenti #</strong>
      <%= number_with_delimiter(supplier_order.items.count, delimiter: ".") %>
    </div>
    <div class="px-4 bg-gray-dark p-2 rounded">
      <strong class="block font-bold mb-1">Quantita' #</strong>
      <%= number_with_delimiter(
        supplier_order.supplier_order_lines.sum(:quantity).to_i,
        delimiter: ".",
      ) %>
    </div>
  </div>
  <% if action_name != "show" %>
    <%= link_to "Show this supplier order", supplier_order, class: "btn-primary" %>
    <%= link_to "Edit this supplier order",
    edit_supplier_order_path(supplier_order),
    class: "btn-positive" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/supplier_orders/_supplier_order_lines.html.erb
<% session["supplier_order_#{@bill_of_material.id}_supplier_order_lines"].each do | line | %>
  <tr id="<%= line[:code] %>" is="turbo-frame" class="bg-blue text-light">
    <td class="px-6 py-4 font-medium whitespace-nowrap">
      <%= line[:code] %>
    </td>
    <td
      scope="row"
      class="
        px-6 py-4 font-medium text-blue-50 whitespace-nowrap dark:text-blue-100
      "
    >
      <%= line[:name] %>
    </td>
    <td class="px-6 py-4 text-center">
      <%= line[:quantity] %>
    </td>
    <td class="px-6 py-4 text-center">
      <%= line[:ordered] %>
    </td>
    <td class="px-6 py-4 text-center">
      <%= line[:to_order] %>
    </td>
  </tr>
<% end %>

app/views/supplier_orders/_supplier_orders.html.erb
<table
  class="
    w-full text-sm text-left rtl:text-right text-blue-100 dark:text-blue-100
  "
>
  <thead class="text-xs text-light uppercase bg-gray-dark dark:text-white">
    <tr>
      <th scope="col" class="px-6 py-3">
        Data
      </th>
      <th scope="col" class="px-6 py-3">
        Numero
      </th>
      <th scope="col" class="px-6 py-3">
        Fornitore
      </th>
      <th scope="col" class="px-6 py-3">
      </th>
    </tr>
  </thead>
  <tbody class="bg-blue text-light">
    <% supplier_orders.each do | supplier_order | %>
      <tr
        data-href="<%= supplier_order_path(supplier_order.id) %>"
        class="bg-blue-500 border-b border-blue-400"
      >
        <td
          scope="row"
          class="
            px-6 py-4 font-medium text-blue-50 whitespace-nowrap dark:text-blue-100
          "
        >
          <%= supplier_order.date %>
        </td>
        <td class="px-6 py-4">
          <%= supplier_order.number %>
        </td>
        <td class="px-6 py-4">
          <%= supplier_order.supplier.name %>
        </td>
        <td class="px-6 py-4">
          <%= link_to "Mostra",
          supplier_order_path(supplier_order.id),
          class: "bg-gray hover:bg-gray-dark float-right text-white rounded p-2" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/supplier_orders/add_component_to_supplier_order.turbo_stream.erb
<% if notice %>
  <%= turbo_stream.append 'notifications' do %>
    <%= render "layouts/notice" %>
  <% end %>
<% end %>

<% if alert %>
  <%= turbo_stream.append 'notifications' do %>
    <%= render "layouts/alert" %>
  <% end %>
<% end %>

app/views/supplier_orders/clear_supplier_order.turbo_stream.erb
<%= turbo_stream.update "supplier_order_lines" do %>
  <%= render partial: "supplier_orders/supplier_order_lines",
  locals: {
    supplier_order_lines:
      session["supplier_order_#{@bill_of_material.id}_supplier_order_lines"],
  } %>
<% end %>

<%= turbo_stream.update "component_buttons" do %>
  <%= render partial: "supplier_orders/supplier_component_buttons",
  locals: {
    bill_of_material_lines:
      session["bill_of_material_#{@bill_of_material.id}_bill_of_material_lines"],
  } %>
<% end %>

<% if notice %>
  <%= turbo_stream.append 'notifications' do %>
    <%= render "layouts/notice" %>
  <% end %>
<% end %>

<% if alert %>
  <%= turbo_stream.append 'notifications' do %>
    <%= render "layouts/alert" %>
  <% end %>
<% end %>

app/views/supplier_orders/edit.html.erb
<div class="mx-auto w-full p-4">
  <%= render "form", supplier_order: @supplier_order %>
  <div class="grid grid-cols-4 gap-4">
    <div class="col-span-3">
      <div class="overflow-x-auto shadow-md rounded-lg bg-blue">
        <table class="w-full text-sm text-left text-light rounded-lg">
          <thead class="text-xs text-light bg-gray-dark uppercase">
            <tr>
              <th scope="col" class="px-6 py-3">
                Gruppo
              </th>
              <th scope="col" class="px-6 py-3">
                Codice
              </th>

              <th scope="col" class="px-6 py-3 text-center">
                Qta'
              </th>
              <th scope="col" class="px-6 py-3 text-center">
                Ord
              </th>
              <th scope="col" class="px-6 py-3 text-center">
                Da ord
              </th>
              <th scope="col" class="px-6 py-3 text-center">
                Allegati
              </th>
              <th scope="col" class="px-6 py-3 text-center">
              </th>
            </tr>
          </thead>
          <tbody id="supplier_order_lines" is="turbo-stream">
            <%= render @supplier_order.supplier_order_lines %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="overflow-y-scroll h-screen">
      <% @component_buttons.each do | line | %>

        <%= render partial: "supplier_orders/supplier_component_buttons",
        locals: {
          line: line,
        } %>
      <% end %>
    </div>
  </div>
  <%= link_to "Show this supplier order", @supplier_order, class: "btn-primary" %>
  <%= link_to "Back to supplier orders", supplier_orders_path, class: "btn-primary" %>
</div>

app/views/supplier_orders/index.html.erb
<div class="w-full h-min-screen p-4">
  <% if notice.present? %>
    <p
      class="
        py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block
      "
      id="notice"
    ><%= notice %></p>
  <% end %>

  <div id="supplier_orders" class="min-w-full">
    <div class="mx-auto w-full">
      <div class="flex justify-between items-center h-full mb-4">
        <h1 class="font-bold text-4xl text-gray-dark">Ordini Fornitori</h1>

      </div>
    </div>
  </div>
  <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <% if @supplier_orders.count.positive? %>
      <%= render "supplier_orders/supplier_orders", supplier_orders: @supplier_orders %>
    <% else %>
      <p class="p-2 text-xl">Non ci sono ancora ordini fornitori. Per iniziare a crearne apri una
        distinta e clicca
        <strong>Nuovo Ordine Fornitore
        </strong></p>
    <% end %>
  </div>

app/views/supplier_orders/new.html.erb
<div class="p-4 w-full">
  <h1 class="font-bold text-4xl text-gray-dark">Nuovo Ordine Fornitore</h1>
  <%= render "form", supplier_order: @supplier_order %>
  <div class="">
    <div class="grid grid-cols-3 gap-2 h-screen">
      <div class="col-span-2 sticky top-0 overflow-y-scroll">
        <% if @supplier_order.supplier_order_lines.count > 0 %>
          <div class="overflow-x-auto shadow-md rounded-lg bg-blue">
            <table class="w-full text-sm text-left text-light rounded-lg">
              <thead class="text-xs text-light bg-gray-dark uppercase ">
                <tr>
                  <th scope="col" class="px-6 py-3">
                    Codice
                  </th>
                  <th scope="col" class="px-6 py-3">
                    Nome
                  </th>
                  <th scope="col" class="px-6 py-3 text-center">
                    Qta'
                  </th>
                  <th scope="col" class="px-6 py-3 text-center">
                    Ord
                  </th>
                  <th scope="col" class="px-6 py-3 text-center">
                    Da ord
                  </th>
                </tr>
              </thead>
              <tbody id="supplier_order_lines" is="turbo-frame">
                <%= render partial: "supplier_orders/supplier_order_lines",
                lines: @supplier_order.supplier_order_lines %>
              </tbody>
            </table>
          </div>
        <% else %>
          <p>L'ordine e' ancora vuoto. Clicca sui componenti a destra per
            aggiungerli.</p>
        <% end %>
      </div>
      <div id="component_buttons" is="turbo-frame" class="overflow-y-scroll h-screen">
        <%= render partial: "supplier_orders/supplier_component_buttons",
        locals: {
          bill_of_material_lines:
            @supplier_order.bill_of_material.bill_of_material_lines,
        } %>
      </div>
    </div>
  </div>
</div>

app/views/supplier_orders/show.html.erb
<%= render @supplier_order %>
<div class="m-4 overflow-x-auto shadow-md rounded-lg bg-blue">
  <table class="w-full text-sm text-left text-light ">
    <thead class="text-xs text-light bg-gray-dark uppercase ">
      <tr>
        <th scope="col" class="px-6 py-3">
          Gruppo
        </th>
        <th scope="col" class="px-6 py-3">
          Codice
        </th>
        <th scope="col" class="px-6 py-3 text-center">
          Qta'
        </th>
        <th scope="col" class="px-6 py-3 text-center">
          Ord
        </th>
        <th scope="col" class="px-6 py-3 text-center">
          Da Ord
        </th>
        <th scope="col" class="px-6 py-3 text-center">
          Allegati
        </th>
      </tr>
    </thead>
    <tbody>
      <%= render @supplier_order.supplier_order_lines %>
    </tbody>
  </table>
</div>
<div class="flex gap-2 float-right p-4">
  <%= button_to "Distruggi",
  supplier_order_path(@supplier_order),
  method: :delete,
  class: "btn-negative" %>
  <%= link_to "Indietro", supplier_orders_path, class: "btn-primary" %>
</div>