config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :order_lines
  resources :orders
  resources :purchase_orders
  resources :sales_orders

  resources :supplier_order_lines
  resources :supplier_orders
  resources :suppliers
  resources :items
  resources :bill_of_material_lines
  resources :bill_of_materials do
    post :import, on: :collection
    get 'components'
    get 'groups'
    get 'import_purchase_order'
    get 'purchase_order_groups'
  end
  get 'components_csv', action: :components, controller: 'bill_of_materials'
  get 'groups_csv', action: :groups, controller: 'bill_of_materials'
  get 'purchase_order_groups_csv', action: :purchase_order_groups, controller: 'bill_of_materials'
  get 'add_component_to_supplier_order', action: :add_component_to_supplier_order, controller: 'purchase_orders'
  get 'send_purchase_order_email', action: :send_email, controller: 'purchase_orders'
  get 'clear_supplier_order', action: :clear_supplier_order, controller: 'supplier_orders'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'bill_of_materials#index'
end

app/models/order_line.rb
class OrderLine < ApplicationRecord
  belongs_to :order, inverse_of: :order_lines
  belongs_to :item
  has_one :order_line_quantity, dependent: :destroy

  # def update_ordered_quantities
  #   return unless order.is_a?(PurchaseOrder) && order.sourceable.is_a?(SalesOrder)

  #   line = order.sourceable.order_lines.find_by(item_id:)
  #   quantities = line.order_line_quantity

  #   quantities.update!(ordered: quantities.ordered + 1)
  #   quantities.update!(to_order: quantities.to_order - 1)
  # end
end

app/controllers/order_lines_controller.rb
class OrderLinesController < ApplicationController
  before_action :set_order_line, only: %i[ show edit update destroy ]

  # GET /order_lines
  def index
    @order_lines = OrderLine.all
  end

  # GET /order_lines/1
  def show
  end

  # GET /order_lines/new
  def new
    @order_line = OrderLine.new
  end

  # GET /order_lines/1/edit
  def edit
  end

  # POST /order_lines
  def create
    @order_line = OrderLine.new(order_line_params)

    if @order_line.save
      redirect_to @order_line, notice: "Order line was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /order_lines/1
  def update
    if @order_line.update(order_line_params)
      redirect_to @order_line, notice: "Order line was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /order_lines/1
  def destroy
    @order_line.destroy!
    redirect_to order_lines_url, notice: "Order line was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_line
      @order_line = OrderLine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_line_params
      params.require(:order_line).permit(:order_id, :item_id, :quantity)
    end
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/views/order_lines/_form.html.erb
<%= form_with(model: order_line, class: "contents") do |form| %>
  <% if order_line.errors.any? %>
    <div
      id="error_explanation"
      class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3"
    >
      <h2><%= pluralize(order_line.errors.count, "error") %>
        prohibited this order_line from being saved:</h2>

      <ul>
        <% order_line.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :order_id %>
    <%= form.text_field :order_id,
                    class:
                      "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :item_id %>
    <%= form.text_field :item_id,
                    class:
                      "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :quantity %>
    <%= form.text_field :quantity,
                    class:
                      "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class:
                  "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/order_lines/_order_line.html.erb
<tr id="<%= dom_id order_line %>" class="bg-blue text-light">

  <td class="px-6 py-4 font-medium whitespace-nowrap">
    <%= order_line.item.code %>
  </td>
  <td class="px-6 py-4 font-medium whitespace-nowrap">
    <%= order_line.item.name %>
  </td>

  <td scope="row" class="px-6 py-4 font-medium whitespace-nowrap">
    <% if order_line.item.pdf_url %>
      <%= link_to "PDF", "#{order_line.item.pdf_url}", class: "btn-positive" %>
      <%= link_to "DXF", "#{order_line.item.dxf_url}", class: "btn-positive" %>
    <% end %>
  </td>
  <td class="px-6 py-4 text-center">
    <% if action_name == 'edit' %>
      <%= link_to order_line_path, class: "btn-primary" do %>
        <i class="fa-solid fa-trash bg-gray"></i>
      <% end %>
    <% end %>

  </td>
</tr>

app/views/order_lines/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing order line</h1>

  <%= render "form", order_line: @order_line %>

  <%= link_to "Show this order line", @order_line, class: "btn-primary" %>
  <%= link_to "Back to order lines", order_lines_path, class: "btn-primary" %>
</div>

app/views/order_lines/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p
      class="
        py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block
      "
      id="notice"
    ><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Order lines</h1>
    <%= link_to "New order line",
    new_order_line_path,
    class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="order_lines" class="min-w-full">
    <%= render @order_lines %>
  </div>
</div>

app/views/order_lines/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New order line</h1>
  <%= render "form", order_line: @order_line %>
  <%= link_to "Back to order lines", order_lines_path, class: "btn-primary" %>
</div>

app/views/order_lines/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p
        class="
          py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block
        "
        id="notice"
      ><%= notice %></p>
    <% end %>

    <%= render @order_line %>

    <%= link_to "Edit this order_line",
    edit_order_line_path(@order_line),
    class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this order_line",
      order_line_path(@order_line),
      method: :delete,
      class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to order_lines",
    order_lines_path,
    class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>