config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :order_lines
  resources :orders
  resources :purchase_orders
  resources :sales_orders

  resources :supplier_order_lines
  resources :supplier_orders
  resources :suppliers
  resources :items
  resources :bill_of_material_lines
  resources :bill_of_materials do
    post :import, on: :collection
    get 'components'
    get 'groups'
    get 'import_purchase_order'
    get 'purchase_order_groups'
  end
  get 'components_csv', action: :components, controller: 'bill_of_materials'
  get 'groups_csv', action: :groups, controller: 'bill_of_materials'
  get 'purchase_order_groups_csv', action: :purchase_order_groups, controller: 'bill_of_materials'
  get 'add_component_to_supplier_order', action: :add_component_to_supplier_order, controller: 'purchase_orders'
  get 'send_purchase_order_email', action: :send_email, controller: 'purchase_orders'
  get 'clear_supplier_order', action: :clear_supplier_order, controller: 'supplier_orders'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'bill_of_materials#index'
end

app/models/sales_order.rb
class SalesOrder < Order
  has_many :sales_order_lines, class_name: 'SalesOrderLine', foreign_key: 'order_id', dependent: :destroy
  has_many :purchase_orders, as: :sourceable
  auto_increment :number, initial: "OC-#{Date.today.year}-0001"
end

app/controllers/sales_orders_controller.rb
class SalesOrdersController < OrdersController
  before_action :set_order, only: %i[show edit update destroy]

  # GET /orders
  def index
    @sales_orders = SalesOrder.where(receivable: current_company)
  end

  # GET /orders/1
  def show; end

  # GET /orders/new
  def new
    @order = PurchaseOrder.new(date: Date.today)
    @suppliers = Supplier.all
  end

  # GET /orders/1/edit
  def edit; end

  # POST /orders
  def create
    @order = PurchaseOrder.new(order_params)
    @order.receivable_type = 'Supplier'
    @order.sendable = current_company

    if @order.save
      redirect_to @order, notice: 'Order was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /orders/1
  def update
    if @order.update(order_params)
      redirect_to @order, notice: 'Order was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /orders/1
  def destroy
    @order.destroy!
    redirect_to orders_url, notice: 'Order was successfully destroyed.', status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = SalesOrder.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def order_params
    params.require(:sales_order).permit(:date, :number, :sendable_id, :receivable_id, :type)
  end
end

app/views/sales_orders/_sales_order.html.erb
<div id="<%= dom_id sales_order %>">
  <% if action_name == "show" %>
    <div class="flex justify-between items-center">
      <h1 class="p-4 font-bold text-4xl text-gray-dark">Ordine Cliente
        <%= sales_order.number %></h1>
      <div class="flex gap-2">
        <%= if sales_order.sourceable.present?
          link_to "Nuovo ordine fornitore",
          new_purchase_order_path(sales_order_id: sales_order.id),
          class: "btn-positive"
        end %>

      </div>
    </div>
    <div class="flex gap-2 text-light mt-4 p-4">
      <div class="px-4 bg-gray-dark p-2 rounded">
        <strong class="block font-bold mb-1">Cliente</strong>
        <%= sales_order.sendable.name %>
      </div>
      <div class="px-4 bg-gray-dark p-2 rounded">
        <strong class="block font-bold mb-1">Data</strong>
        <%= sales_order.date %>
      </div>
      <div class="px-4 bg-gray-dark p-2 rounded">
        <strong class="block font-bold mb-1">Numero</strong>
        <%= sales_order.number %>
      </div>
      <div class="px-4 bg-gray-dark p-2 rounded">
        <strong class="block font-bold mb-1">Distinta</strong>
        <%= sales_order.sourceable.number %>
      </div>
      <div class="px-4 bg-gray-dark p-2 rounded">
        <strong class="block font-bold mb-1">Componenti #</strong>
        <%= number_with_delimiter(sales_order.items.count, delimiter: ".") %>
      </div>

    </div>
    <div class="m-4 overflow-x-auto shadow-md rounded-lg bg-blue">

      <table class="w-full text-sm text-left text-light ">
        <thead class="text-xs text-light bg-gray-dark uppercase ">
          <tr>
            <th scope="col" class="px-6 py-3">
              Codice
            </th>
            <th scope="col" class="px-6 py-3">
              Nome
            </th>
            <th scope="col" class="px-6 py-3 text-center">
              Qta'
            </th>
            <th scope="col" class="px-6 py-3 text-center">
            </th>
          </tr>
        </thead>
        <tbody>
          <%= render sales_order.sales_order_lines %>
        </tbody>
      </table>
    </div>
    <%= button_to "Elimina",
    order_path(sales_order),
    method: :delete,
    class: "btn-negative" %>

  <% else %>
    <tr
      data-href="<%= supplier_order_path(sales_order.id) %>"
      class="bg-blue border-b border-blue-400 text-light"
    >
      <td scope="row" class=" px-6 py-4 font-medium whitespace-nowrap ">
        <%= sales_order.date %>
      </td>
      <td class="px-6 py-4">
        <%= sales_order.number %>
      </td>
      <td class="px-6 py-4">
        <%= sales_order.sendable.name %>
      </td>
      <td class="px-6 py-4 text-right">
        <%= link_to "Mostra", sales_order_path(sales_order.id), class: "btn-primary" %>
      </td>
    </tr>
  <% end %>
</div>

app/views/sales_orders/index.html.erb
<div class="w-full h-min-screen p-4">
  <h1 class="font-bold text-4xl text-gray-dark">Ordini Clienti</h1>
  <div class="relative overflow-x-auto shadow-md sm:rounded-lg mt-4">
    <table class="w-full text-sm text-left rtl:text-right">
      <thead class="sticky top-0 text-xs text-light uppercase bg-gray-dark">
        <tr>
          <th scope="col" class="px-6 py-3">
            Data
          </th>
          <th scope="col" class="px-6 py-3">
            Numero
          </th>
          <th scope="col" class="px-6 py-3">
            Cliente
          </th>
          <th scope="col" class="px-6 py-3">

          </th>
        </tr>
      </thead>
      <tbody id="orders" is="turbo-stream">
        <%= render @sales_orders %>
      </tbody>
    </table>
  </div>
</div>